<!-- Powered by LIMB | http://www.limb-project.com/ -->
<!-- Designed by BIT | http://www.bit-creative.com/ -->
<html>
<head>
  <base href="<?= LIMB_HTTP_BASE_PATH ?>"/>
  <title>{$#title} :: Limb shop example application on &#123;&#123;macro&#125;&#125;</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
  <link rel=stylesheet type="text/css" href="styles/main.css"/>
</head>
<body>

<div id="header">
  <div class="center">
    <img src="images/logo.limb.gif"  width='384' height='46' alt='logo.limb' id='logo'/>
    <span>control panel</span>
    <div id="limb_links"><a href="http://limb-project.com">limb-project.com</a>&nbsp;|&nbsp;<a href="http://bits.limb-project.com">bits.limb-project.com</a></div>
  </div>
</div>



 <div id="center">

  <div id="wrapper" >

    <div id="container">
      <div id="content">
        <h1>{$#title}</h1>

        {{include file='flash_box.phtml' /}}

        {{slot id='content'/}}
      </div>
    </div>

    <div id="sidebar">
      <div id="navigation">
        <ul>
          <li><a href="admin_product">Products</a></li>
          <li><a href="admin_order">Orders</a></li>
          <li><a href="admin_user">Users</a></li>
        </ul>
      </div>

      <dl id="profile">
        <dt>Profile</dt>
        <dd>
          <core:datasource from='#user'>
          User: {$#user.name}<br/>
          Login: {$#user.login}<br/>
          Email: {$#user.email}<br/>
          <a href="{{route_url params='controller:login,action:logout'}}">logout</a>
          </core:datasource>
        </dd>
      </dl>

    </div>

  </div>
</div>

</body>
</html>

