<html>
<head>
  <title>{$#title} :: Limb3 shop example application on &#123;&#123;macro&#125;&#125;</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
  <link rel=stylesheet type="text/css" href="http://bits.limb-project.com/shop/styles/main.css"/>
</head>
<body>

<div id="header">
  <div class="center">
    <img src="http://bits.limb-project.com/shop/images/logo.limb.gif"  width='384' height='46' alt='logo.limb' id='logo'/>
    <div id="limb_links"><a href="http://limb-project.com">limb-project.com</a>&nbsp;|&nbsp;<a href="http://bits.limb-project.com">bits.limb-project.com</a></div>
  </div>
</div>

 <div id="center">
  <div id="wrapper" >

    <div id="container">
      <div id="content">
        <h1>{$#title}</h1>

        {{include file='flash_box.phtml'/}}

        {{slot id='content'/}}
      </div>
    </div>

    <div id="sidebar">

      <div id="navigation">
        <ul>
          <li><a href="product">Products</a></li>
          <li><a href="cart">Your Cart</a></li>
        </ul>
      </div>

      <dl id="profile">
        <dt>Profile</dt>
        <dd>
					<?php
					  $user = lmbToolkit :: instance()->getUser();
					 if($user->is_logged_in) { ?>
					  Logged in as :{$user.name}
					<? } ?>
			  </dd>
			</dl>

    </div>
  </div>
</div>
</body>
</html>