{{pager id="pager" items="5"}}

<table width='690' border='0' cellspacing='0' cellpadding='0' class='pager'>
<tr>
  <td width='50%' align='left'>
  {{pager:first}}<a href="{$href}" title="First page">&#60;&#60;&nbsp;</a>{{/pager:first}}

  {{pager:prev}}<a href="{$href}" title="Previous page">&#60;&nbsp;</a>{{/pager:prev}}

  {{pager:list}}

    {{pager:current}}&nbsp;<b>[&nbsp;{$number}&nbsp;]</b>&nbsp;{{/pager:current}}
    {{pager:number}}<a href="{$href}">&nbsp;{$number}&nbsp;</a>{{/pager:number}}

  {{/pager:list}}

  &nbsp;
  {{pager:next}}<a href="{$href}" title="Next page">&#62;</a>{{/pager:next}}
  &nbsp;
  {{pager:last}}<a href="{$href}" title="Last page">&#62;&#62;</a>{{/pager:last}}
  </td>
  <td align='right'>
    Shown: from <b>{$begin_item_number}</b> to <b>{$end_item_number}</b>
    Total: <b>{$total_items}</b><br />
  </td>
</tr>
</table>

{{/pager}}

