<? $this->title = 'Registration'; ?>
{{wrap with="front_page_layout.phtml" in="content"}}

{{form id='register_form' name='register_form' method='post'}}

  {{include file='form_errors.phtml'/}}

  <div class="field">
  <label for="login" errorclass='error'>Login<span class='star'>*</span>:</label>
  {{input name="login" id='login' type="text" title="Login" class='input'/}}
  </div>

  <div class="field">
  <label for="name" errorclass='error'>Name<span class='star'>*</span>:</label>
  {{input name="name" id='name' type="text" title="Name" class='input'/}}
  </div>

  <div class="field">
  <label for="email" errorclass='error'>Email<span class='star'>*</span>:</label>
  {{input name="email" id='email' type="text" title="Email" class='input'/}}
  </div>

  <div class="field">
  <label for="password" errorclass='error'>Password<span class='star'>*</span>:</label>
  {{input name="password" id='password' type="password" title="Password" class='input'/}}
  </div>

  <div class="field">
  <label for="repeat_password" errorclass='error'>Repeat password<span class='star'>*</span>:</label>
  {{input name="repeat_password" id="repeat_password" type="password" title="Repeat password" class='input'/}}
  </div>

  <div class="field">
  <label for="address" errorclass='error'>Delivery address:</label>
  {{textarea name="address" id='address' type="text" title="Delivery address"  size='40' class='textarea'/}}
  </div>

   <div class="hr"></div>
   <input id='register' type='submit' value='Register'/>
{{/form}}

{{/wrap}}
