<? $this->title ='Checkout'; ?>

{{wrap with="front_page_layout.phtml" in="content_zone"}}

Your cart contains {$#cart.items_count} items.

{{list using="$#cart.items"}}
<table cellpadding="0" cellspacing="0" class='list'>
  <thead>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Summ</th>
  </tr>
  </thead>
  {{list:item}}
  <tr class='checkout'>
   <td>{$item.product.title}</td>
   <td>${$item.price|number:2, '.', ' '}</td>
   <td>{$item.quantity}</td>
   <td>${$item.summ|number:2, '.', ' '}</td>
  </tr>
  {{/list:item}}
</table>
{{/list}}

Total summ is : <b>${$#cart.total_summ|number:2, '.', ' '}</b>

<br/>
{{form name='checkout_form' id='checkout_form' method='POST'}}

  <label for='address'>Delivery address:</label><br/>
  {{textarea type="text" name="address" id="address" title="Delivery address"/}}<br/>

  <input type='submit' class='button' name='submitted' value="Finish order" class='button'/><br/>
{{/form}}
{{/wrap}}