<? $this->title ='Your Cart'; ?>
{{wrap with="front_page_layout.phtml" in="content_zone"}}

<? if($this->cart->items_count) {?>
Your cart contains {$#cart.items_count} items.

{{list using="$#cart.items" parity="$parity"}}
<table cellpadding="0" cellspacing="0" class='list'>
  <thead>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Summ</th>
  </tr>
  </thead>
  {{list:item}}
  <tr class='{$parity}'>
   <td>{$item.product.title}</td>
   <td>${$item.price|number:2, '.',' '}</td>
   <td>{$item.quantity}</td>
   <td>${$item.summ|number:2, '.', ' '}</td>
  </tr>
  {{/list:item}}
</table>
{{/list}}

Total summ is : <b>${$#cart.total_summ|number:2, '.', ' '}</b>
<br/>
<a href="{{route_url params='action:empty'}}">Empty cart</a><br/>
<a href="{{route_url params='action:checkout'}}">Checkout</a>

<? } else { ?>
You cart is empty at the moment!
<? } ?>
{{/wrap}}