<div class="field">
  <label for="title">Title:</label>
  {{input name='title' type='text' title='Title' size='50' class='input'/}}<br/>
</div>
<div class="field">
  <label for="price">Price:</label>
  {{input name='price' type='text' title='Price' size='20' class='input'/}}<br/>
</div>
<div class="field">
  <label for="is_available">Available at the moment?:</label>
  {{js_checkbox name='is_available' class='input'/}}<br/>
</div>
<div class="field">
  <label for="description">Description:</label>
  {{textarea name='description' rows='2' title='Description' cols='40' rows='8' class='input'/}}<br/>
</div>
<div class="field">
  <label for="image">Image:</label>
  {{input name="image" type="file" size="40" class='input'/}}<br/>
</div>
<div class="field">
  <? if($this->product->getImagePath()) { ?>
    <img src='{$#product.image_path}' class='img' />
  <? } ?>
  Specify image file path to upload new image.
</div>
<div class="hr"></div>

