<? $this->title = 'Your profile'; ?>
{{wrap with="front_page_layout.phtml" in="content"}}

This is your profile page. You can change some of your profile fields as well as your password<br/>

<h2>Profile</h2>

{{form id='profile_form' name='profile_form' method='post'}}

  {{include file='form_errors.phtml'/}}

  <label for="name" errorclass='error'>Name:</label><br/>
  {{input name="name" id='name' type="text" title="Name" class='input'/}}<br/>

  <label for="email" errorclass='error'>Email:</label><br/>
  {{input name="email" id='email' type="text" title="Email" class='input'/}} <br/>

  <label for="address" errorclass='error'>Delivery address:</label><br/>
  {{textarea name="address" id='address' type="text" title="Delivery address" cols='40' rows='5' class='input'/}} <br/>

  <input id='edit' name='edit' type='submit' value='Update profile'/>
{{/form}}

<h2>Password change form</h2>

{{form id='change_password_form' name='change_password_form' method='post'}}

  {{include file='form_errors.phtml'/}}

   <label for="old_password" errorclass='error'>Old Password:</label><br/>
   {{input name="old_password" id='old_password' type="password" title="Old Password" class='input'/}}<br/>

   <label for="password" errorclass='error'>Password:</label><br/>
   {{input name="password" id='password' type="password" title="Password" class='input'/}}<br/>

   <label for="repeat_password" errorclass='error'>Repeat password:</label><br/>
   {{input name="repeat_password" id="repeat_password" type="password" title="Repeat password" class='input'/}}<br/>

   <input id='change_password' name='change_password' type='submit' value='Change password'/>
{{/form}}

{{/wrap}}
