<? $this->title='Login'; ?>
{{wrap with="front_page_layout.phtml" into="content_zone"}}
{{form method="POST" id='login_form'}}

  {{include file='_admin/form_errors.phtml'/}}

  <div class="field">
  <label for='login'>Login:</label>
  {{input type="text" name="login" id="login" title="Login"/}}
  </div>

  <div class="field">
  <label for='passwd'>Password:</label>
  {{input type="text" name="password" id="password" type="password" title="Password"/}}
  </div>

  <input type='submit' class='button' name='submitted' value="Submit" class='button'/>

{{/form}}
{{/wrap}}