<? $this->title ='Your orders'; ?>
{{wrap with="front_page_layout.phtml" in="content_zone"}}

{{list using='$#toolkit.user.orders' parity="$parity"}}
	<table cellpadding="0" cellspacing="0" class='list'>
	  <thead>
	  <tr>
	    <th>#</th>
	    <th>Date</th>
	    <th>Summ</th>
	    <th>Status</th>
	  </tr>
	  </thead>
	  {{list:item}}
	  <tr class="{$parity}">
	   <td><a href="{{route_url params='action:show_order,id:{$item.id}'}}">{$item.id}</a></td>
	   <td><a href="{{route_url params='action:show_order,id:{$item.id}'}}">{$item.date|date:"F j, Y, G:i"}</a></td>
	   <td>${$item.summ|number:2, '.', ' '}</td>
	   <td>{$item.status_name}</td>
	  </tr>
	  {{/list:item}}
	</table>
  {{list:empty}}
    You made no orders in our shop yet.
  {{/list:empty}}
{{/list}}
{{/wrap}}