<? $this->title ='Order details'; ?>

{{wrap with="front_page_layout.phtml" in="content_zone"}}

{{list using='$#order.lines' parity="$parity"}}
<table cellpadding="0" cellspacing="0" class='list'>
  <thead>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Summ</th>
  </tr>
  </thead>
  {{list:item}}
  <tr class='{$parity}'>
   <td>{$item.product.title}</td>
   <td>${$item.price|number:2, '.', ' '}</td>
   <td>{$item.quantity}</td>
   <td>${$item.summ|number:2, '.', ' '}</td>
  </tr>
  {{/list:item}}
</table>
{{/list}}
{{/wrap}}