<? $this->title='Create user'; ?>
{{wrap with="admin_page_layout.phtml" in="content_zone"}}

{{form id='user_form' name='user_form' method='post'}}

  {{include file='form_errors.phtml'/}}

   <div class="field">
   <label for="password">Password:</label>
   {{input name="password" type="password" title="Password" class="req"/}}
   </div>

   <div class="field">
   <label for="repeat_password">Repeat password:</label>
   {{input name="repeat_password" type="password" title="Repeat password" class="req"/}}
   </div>

   {{include file='admin_user/form_fields.phtml'/}}

   <input id='create' name='create' type='submit' value='Create'/>
{{/form}}

{{/wrap}}
