<div class="field">
<label for="login">Login:</label>
{{input name="login" type="text" title="Login" class="input"/}}
</div>

<div class="field">
<label for="name">Name:</label>
{{input name="name" type="text" title="Name" class="input"/}}
</div>

<div class="field">
<label for="email">Email:</label>
{{input name="email" type="text" title="Email" class="input"/}}
</div>

<div class="field">
<label for="email">Is admin:</label>
{{js_checkbox id='is_admin' name='is_admin' class="input"/}}
</div>

<div class="hr"></div>


