<? $this->title='Change user password'; ?>
{{wrap with='admin_page_layout.phtml' in='content_zone'}}

{{form method="post" name="user_form" id="user_form"}}

  {{include file='form_errors.phtml'/}}

  <div class='field'>
  <label for="password">New password:</label>
  {{input name="password" type="password" title="New password" class="input"/}}
  </div>

  <div class='field'>
  <label for="repeat_password">Repeat password:</label>
  {{input name="repeat_password" type="password" title="Repeat password" class="input"/}}
  </div>

  <input type="submit" name="submitted" value="Change password"/>

{{/form}}

{{/wrap}}
