<? $this->title='Users'; ?>
{{wrap with="admin_page_layout.phtml" in="content_zone"}}

<a href="{{route_url params='action:create'}}">Create user</a>

<? $users = lmbActiveRecord :: find('User'); ?>

{{paginate iterator='$users' pager='pager'/}}

{{include file='pager.phtml'/}}

{{list using='$users' as="$user" parity='$parity'}}
<table  cellspacing=0 cellpadding=0 class='list'>
<thead>
<tr>
  <th>Name</th>
  <th>Login</th>
  <th>E-mail</th>
  <th>Actions</th>
</tr>
</thead>
<tbody>
{{list:item}}
<tr class='{$parity}'>
  <td>{$user.name}</td>
  <td>{$user.login}</td>
  <td><a href='mailto:{$user.email}'>{$user.email}</a></td>
  <td>
    <a href="{{route_url params='action:change_password,id:{$user.id}'}}">Change password</a>
    <a href="{{route_url params='action:edit,id:{$user.id}'}}">Edit</a>
    <a href="{{route_url params='action:delete,id:{$user.id}'}}">Delete</a>
  </td>
</tr>
{{/list:item}}
</tbody>
</table>
{{/list}}

{{/wrap}}
