{{wrap with="admin_page_layout.phtml" in="content_zone"}}

  {{include file="_admin/selectors.phtml"/}}
  {{include file="_admin_object/actions.phtml"/}}

  <div id="header">
    <h1>Users</h1>
    <div class="header_actions">
      {{apply template="object_action" action="create" is_link="true" title="Create user"/}}
    </div>

    {{include file='_admin/pager.phtml' items='{$this->items}'/}}
  </div>

  <div id="body">

    {{list using="{$#items}" as="$item" counter="$counter" parity='$parity'}}

      <div class='list'>
        <table>
          <tr>
            <th>#ID</th>
            <th>Name</th>
            <th>Login</th>
            <th>Email</th>
            <th>Address</th>
            <th>Actions</th>
          </tr>

          {{list:item}}
            <tr class="{$parity}">
              <td>{$item.id}</td>
              <td>{$item.name}</td>
              <td>{$item.login}</td>
              <td>{$item.email}</td>
              <td>{$item.address|raw|nl2br}</td>
              <td class='actions'>
                {{apply template="object_action_edit" item="{$item}"/}}
                {{apply template="object_action_delete" item="{$item}"/}}
              </td>
            </tr>
          {{/list:item}}
          {{list:empty}}
            <div class="empty_list">Empty</div>
          {{/list:empty}}
        </table>
      </div>

    {{/list}}

  </div>

{{/wrap}}