{{wrap with="page.phtml" into="page_placeholder"}}
<h1>Newsline.</h1>


<a href='{{route_url params="action:create"/}}'>Create news</a>
<p/>

{{include file='pager.phtml' /}}


{{list using='$this->news' as='$item'}}
  <table border="1">
  <tr>
    <th>ID</th>
    <th>Date</th>
    <th>Title</th>
    <th>Actions</th>
  </tr>
 {{list:item}}
  <tr>
    <td>{$item.id}</td>
    <td>{$item.date}</td>
    <td>{$item.title}</td>
	<td>
      <a href='{{route_url params="action:edit,id:{$item.id}"/}}'>Edit</a>&nbsp;&nbsp;
      <a href='{{route_url params="action:delete,id:{$item.id}"/}}'>Delete</a>
    </td>
  </tr>
  <tr>
    <td colspan='4'>
      {$item.annotation}
	  <a href="{{route_url params='controller:news,action:detail,id:{$item.id}'}}">more...</a>
    </td>
  </tr>
 {{/list:item}}
  </table>
{{/list}}
{{/wrap}}