<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>YourDomain.com last news</title>
    <language>en</language>
    <description>Last 5 news from our site</description>
    <link>{{route_url/}}</link>
    <atom:link href="{{route_url/}}" rel="self" type="application/rss+xml"/>
    {{list using="$#news" as="$item"}}
    {{list:item}}
    <item>
      <guid isPermaLink="false">g{$item->id}</guid>
      <title>{$item->title}</title>
      <link>{{route_url params="controller:news,action:detail,id:{$item->id}"/}}</link>
      <description>{$item->annotation}</description>
      <pubDate><?=date('r', strtotime($item->date));?></pubDate>
    </item>
    {{/list:item}}
    {{/list}}
  </channel>
</rss>
